spring:
  datasource:
    master:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/test
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/test2
      driver-class-name: com.mysql.cj.jdbc.Driver

  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

